  matrix:
    include:
    - language: php
      php:
        - 5.4
        - 5.5
        - 5.6
      services:
      - mysql
      before_script:
      - travis_retry composer self-update
      - composer install
      - mysql -u root -e  'CREATE DATABASE d1312548;'
      - mysql -u root -e "CREATE user 's1312548'@'localhost' IDENTIFIED BY 's1312548';"
      - mysql -u root -e "GRANT ALL ON d1312548.* TO 's1312548'@'localhost';"
      script:
      - "phpunit --testsuite=unit --coverage-clover coverage.xml"
      after_script:
      - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      - php coveralls.phar --verbose
    - language: python
      sudo: true
      python:
        - "2.6"
        - "2.7"
        - "3.3"
        - "3.4"
        - "3.5"
      install:
        - pip install --upgrade pip
        - pip install coveralls
        - pip install coverage
        - pip install nose
        - pip install Pillow
        - pip3 install --upgrade -r requirements.txt
      script: 
        - nosetests testTryCatch.py --with-coverage
      after_success:
        coveralls
