language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
- travis_retry composer self-update
- composer install
script:
- "phpunit --testsuite=unit --coverage-clover coverage.xml"
after_script:
- wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
- php coveralls.phar --verbose
