language: php
php:
  - 5.4
  - 5.5
  - 5.6
services:
- mysql
before_script:
- travis_retry composer self-update
- composer install
before_install:
- mysql -e 'CREATE DATABASE d1312548;'
- mysql -u root -e "CREATE user 's1312548'@'127.0.0.1' IDENTIFIED BY 's1312538';"
script:
- "phpunit --testsuite=unit --coverage-clover coverage.xml"
after_script:
- wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
- php coveralls.phar --verbose
